export { default as image1 } from "./image1.png";
export { default as image2 } from "./image2.png";
export { default as arrow } from "./arrow.png";
export { default as image3 } from "./image3.png";
export { default as image4 } from "./image4.png";
export { default as image5 } from "./image5.png";
export { default as image6 } from "./image6.png";
export { default as image7 } from "./image7.png";
export { default as image8 } from "./image8.png";
export { default as woman1 } from "./woman1.jpeg";
export { default as woman2 } from "./woman2.jpg";
export { default as arrowleft } from "./arrowleft.png";
export { default as arrowright } from "./arrowright.png";
export { default as star1 } from "./Star 1.png";
export { default as star2 } from "./Star 2.png";
export { default as star3 } from "./Star 3.png";
export { default as star4 } from "./Star 4.png";
export { default as star5 } from "./Star 5.png";
export { default as reactangle } from "./Rectangle.png";
