export { default as Section } from "./Section";
export { default as Relax } from "./Relax";
export { default as Happily } from "./Happily";
export { default as Work } from "./Work";
export { default as Works2 } from "./Works2";
export { default as Africa } from "./Africa";
export { default as Ready } from "./Ready";
export { default as Property } from "./Property";
export { default as Property2 } from "./Property2";
